version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports: 
      - "8989:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/nginx:/var/log/nginx/
    links:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/php.log:/usr/local/var/log/
    links:
      - db
  db:
    image: mysql:8.0.31
    container_name: mysql
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/database/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root