version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php8.2/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/php.log:/usr/local/var/log/
    links:
      - db
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  db:
    image: mysql:8.0.31
    container_name: mysql
    command: ['--authentication_policy=mysql_native_password', '--lower_case_table_names=2']
    restart: always
    volumes:
      - ./db/db/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
  npm:
    image: node:latest
    container_name: npm
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    entrypoint: /bin/sh -c "npm install && npm run dev -- --host"
    networks:
      - app-network
  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
