version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: php
    ports: 
      - "8080:8000"
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/php.log:/usr/local/var/log/
    links:
      - db
  db:
    image: mysql:8.0.31
    container_name: mysql
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/database/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
  npm:
    image: node:latest
    container_name: npm
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    entrypoint: /bin/sh -c "npm install && npm run dev -- --host"