CREATE DATABASE `db_estoque-nti`;
CREATE TABLE `db_estoque-nti`.`entrega`(   `id` INT NOT NULL AUTO_INCREMENT,   `qntde` INT NOT NULL,   `data_entrega` DATE NOT NULL,   `observacao` VARCHAR(100) NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`usuario`(   `id` INT NOT NULL AUTO_INCREMENT,   `nome` VARCHAR(45) NOT NULL,   `cpf` INT NOT NULL,   `email` VARCHAR(50) NOT NULL,   `senha` VARCHAR(16) NOT NULL,   `ativo` TINYINT NOT NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`solicitacao` (   `id` INT NOT NULL AUTO_INCREMENT,   `estado_solicitacao` VARCHAR(15) NOT NULL,   `descricao` VARCHAR(100) NULL,   `data_solicitacao` DATE NOT NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`itens_solicitacao` (   `id` INT NOT NULL AUTO_INCREMENT,   `qntde_item` INT NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`produto` (   `id` INT NOT NULL AUTO_INCREMENT,   `modelo_produto` VARCHAR(45) NOT NULL,   `descricao` VARCHAR(150) NULL,   `qntde_estoque` INT NOT NULL,   `ativo` TINYINT NOT NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`diretoria` (   `id` INT NOT NULL AUTO_INCREMENT,   `nome` VARCHAR(45) NOT NULL,   `ativo` TINYINT NOT NULL,   `data_criacao` DATE NOT NULL,   `data_desativado` DATE NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`divisao` (   `id` INT NOT NULL AUTO_INCREMENT,   `nome` VARCHAR(45) NOT NULL,   `ativo` TINYINT NOT NULL,   `data_criacao` DATE NOT NULL,   `data_desativado` DATE NULL,   PRIMARY KEY (`id`));
CREATE TABLE `db_estoque-nti`.`orgao` (   `id` INT NOT NULL AUTO_INCREMENT,   `nome` VARCHAR(45) NOT NULL,   `ativo` TINYINT NOT NULL,   `data_criacao` DATE NOT NULL,   `data_desativado` DATE NULL,   PRIMARY KEY (`id`));
ALTER TABLE `solicitacao` ADD (  `usuario_id` INT NOT NULL,   INDEX `fk_solicitacao_usuario1_idx` (`usuario_id` ASC) VISIBLE,   CONSTRAINT `fk_solicitacao_usuario1`     FOREIGN KEY (`usuario_id`)     REFERENCES `db_estoque-nti`.`usuario` (`id`));
ALTER TABLE `itens_solicitacao` ADD (   `produto_id` INT NOT NULL,   `solicitacao_id` INT NOT NULL,   INDEX `fk_itens_solicitacao_produto_idx` (`produto_id` ASC) VISIBLE,   INDEX `fk_itens_solicitacao_solicitacao1_idx` (`solicitacao_id` ASC) VISIBLE,   CONSTRAINT `fk_itens_solicitacao_produto`     FOREIGN KEY (`produto_id`)     REFERENCES `db_estoque-nti`.`produto` (`id`),   CONSTRAINT `fk_itens_solicitacao_solicitacao`     FOREIGN KEY (`solicitacao_id`)     REFERENCES `db_estoque-nti`.`solicitacao` (`id`));
ALTER TABLE `entrega` ADD (   `usuario_id` INT NOT NULL,   `itens_solicitacao_id` INT NOT NULL,   INDEX `fk_entrega_usuario1_idx` (`usuario_id` ASC) VISIBLE,   INDEX `fk_entrega_itens_solicitacao1_idx` (`itens_solicitacao_id` ASC) VISIBLE,   CONSTRAINT `fk_entrega_usuario`     FOREIGN KEY (`usuario_id`)     REFERENCES `db_estoque-nti`.`usuario` (`id`),   CONSTRAINT `fk_entrega_itens_solicitacao`     FOREIGN KEY (`itens_solicitacao_id`)     REFERENCES `db_estoque-nti`.`itens_solicitacao` (`id`));
ALTER TABLE `usuario` ADD (   `divisao_id` INT NULL,   `diretoria_id` INT NULL,   INDEX `fk_usuario_diretoria1_idx` (`diretoria_id` ASC) VISIBLE,   INDEX `fk_usuario_divisao1_idx` (`divisao_id` ASC) VISIBLE,   CONSTRAINT `fk_usuario_diretoria`     FOREIGN KEY (`diretoria_id`)     REFERENCES `db_estoque-nti`.`diretoria` (`id`),   CONSTRAINT `fk_usuario_divisao`     FOREIGN KEY (`divisao_id`)     REFERENCES `db_estoque-nti`.`divisao` (`id`));
ALTER TABLE `diretoria` ADD (   `orgao_id` INT NOT NULL,   INDEX `fk_diretoria_orgao1_idx` (`orgao_id` ASC) VISIBLE,   CONSTRAINT `fk_diretoria_orgao`     FOREIGN KEY (`orgao_id`)     REFERENCES `db_estoque-nti`.`orgao` (`id`));
ALTER TABLE `divisao` ADD (   `diretoria_id` INT NULL,   INDEX `fk_divisao_diretoria1_idx` (`diretoria_id` ASC) VISIBLE,   CONSTRAINT `fk_divisao_diretoria`     FOREIGN KEY (`diretoria_id`)     REFERENCES `db_estoque-nti`.`diretoria` (`id`))

